myapp/blog/urls.py
from django.urls import path
from . import views

app_name='blog'

urlpatterns=[
    path('details/<str:slug>',views.detail, name='detail'),
    path('index',views.index, name= 'index'),
    path('new_url',views.new_url_view, name= 'new_page_url'),
    path('old_url',views.old_url_redirect, name= 'old_url'),
    path('contact',views.contact, name= 'contact'),
    path('about',views.about, name= 'about'),
    path('register',views.register, name= 'register'),
    path('login',views.login, name = 'login'),
    path('dashboard',views.dashboard,name='dashboard'),
    path('logout',views.logout,name='logout'),
    path('forgot_password',views.forgot_password,name='forgot_password'),
    path('reset_password/<uidb64>/<token>',views.reset_password,name='reset_password'),

]

myapp/myapp/urls.py
from django.contrib import admin
from django.urls import path,include

handler404 = 'myapp.views.custom_page_not_found'

urlpatterns = [
    path('',include('blog.urls')),
    
    path('admin/', admin.site.urls),
]

myapp/blog/models.py
from django.db import models
from django.utils.text import slugify
# Create your models here.


# Category
class Category (models.Model):
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name


class Post(models.Model):
    title = models.CharField(max_length=100)
    content = models.TextField()
    img_url= models.URLField(null=True) # default length is 200. null argument is used to nullable whch means some post doesn't contain images
    created_at = models.DateTimeField(auto_now_add=True)
    slug = models.SlugField(unique=True)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)


    def save(self,*args,**kwargs):
        self.slug = slugify (self.title)
        super().save(*args,**kwargs)
 

    def __str__(self) :
        return self.title


class AboutUs(models.Model):
    content = models.TextField()

myapp/blog/forms.py
from typing import Any
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth import authenticate
class ContactForm(forms.Form):
    name  = forms.CharField(label='Name', max_length= 100, required=True)
    email = forms.EmailField (label="Email",required=True)
    message = forms.CharField(label="Message",required=True)

class RegisterForm(forms.ModelForm):
    username = forms.CharField(label='Username', max_length=100, required=True)
    email = forms.CharField(label='Email', max_length=100, required=True)
    password = forms.CharField(label='Password', max_length=100, required=True)
    password_confirm = forms.CharField(label='Confirm Password', max_length=100, required=True)

    class Meta:
        model  = User
        fields = ['username','email','password']

    def clean(self):
        cleaned_data  = super().clean()
        password = cleaned_data.get('password')
        password_confirm = cleaned_data.get('password_confirm')

        if password and password_confirm and password !=password_confirm:
            raise forms.ValidationError('Password do not match')

class LoginForm (forms.Form):
    username= forms.CharField(label="username",max_length=100,required=True)
    password= forms.CharField(label="password",max_length=100,required=True)

    def clean(self) :
        cleaned_data = super().clean()
        username = cleaned_data.get("username")
        password = cleaned_data.get("password")
        if username and password:
            user = authenticate(username=username,password=password)
            if user is None:
                raise forms.ValidationError("Invalid Username or Password")
            
class ForgotPasswordForm(forms.Form):
    email = forms.EmailField(label="Email",max_length=254, required=True)

    def clean(self):
        cleaned_data=super().clean()
        email = cleaned_data.get('email')

        if not User.objects.filter(email=email).exists():
            raise forms.ValidationError("no user has registered with this mail")

myapp/blog/views.py
from django.shortcuts import render,redirect
from django.http import HttpResponse,Http404
from django.urls import reverse
import logging

from .models import Post,AboutUs
from django.core.paginator import Paginator
from .forms import ContactForm, ForgotPasswordForm, LoginForm, RegisterForm
from django.contrib import messages
from django.contrib.auth import authenticate,login as auth_login, logout as auth_logout
from django.contrib.auth.models import User
from django.contrib.auth.tokens import default_token_generator

from django.utils.http import urlsafe_base64_encode
from django.utils.encoding import force_bytes
from django.contrib.sites.shortcuts import get_current_site
from django.template.loader import render_to_string
from django.core.mail import send_mail

# Create your views here.
# static demo data
#posts=[
#    {'id':1,'title':'Post 1', 'Content': " Content of Post 1"},
#    {'id':2,'title':'Post 2', 'Content': " Content of Post 2"},
#    {'id':3,'title':'Post 3', 'Content': " Content of Post 3"},
#    {'id':4,'title':'Post 4', 'Content': " Content of Post 4"},
#    ]


def index(request):
    blog_title = "Latest Posts" 
    # getting data from post model
    all_posts = Post.objects.all()
    paginator = Paginator(all_posts,5)
    page_number=request.GET.get('page_no')
    page_obj = paginator.get_page(page_number)

    return render(request,'index.html',{'blog_title': blog_title, 'page_obj':page_obj})


def detail(request,slug):
    #getting static data 
    #post=next((item for item in posts if item['id']==id),None)
 
    try:
    # getting data from model by post id
        post=Post.objects.get(slug=slug)
        related_posts = Post.objects.filter(category = post.category).exclude(pk=post.id)
    except Post.DoesNotExist:
        raise Http404("Post Doesn't Exist")
 
    #logger=logging.getLogger("TESTING")
    #logger.debug(f"post variable is {post}")

    return render (request,'detail.html',{'post':post,'related_posts':related_posts})    


def old_url_redirect(request):
    return redirect(reverse('blog:new_page_url'))


def new_url_view(request):
    return HttpResponse("This is the new urls")

def contact(request):
    if request.method == "POST":
        #logger = logging.getLogger("TESTING")
        form=ContactForm(request.POST)
        name = request.POST.get('name')
        email = request.POST.get('email')
        message = request.POST.get('message')
        if form.is_valid():
           #print("HI")

            #print(name)
            print(email)
            #print(message)
            #logger.debug(f"POST data is {name} {email} {message}")
            success_message = 'Your form has been successfully submitted'
            return render(request,'contact.html',{'form':form, 'success_message':success_message})
        else:
            # Handle invalid form case (optional)
            #print("Invalid form submission.")
            #logger.debug(f"POST data is invalid")
            return render(request,'contact.html',{'form':form, 'name':name, 'email':email, 'message': message})

    return render (request,'contact.html')    

def about(request):
    aboutus_content= AboutUs.objects.first()
    if aboutus_content is None or not aboutus_content.content:
        aboutus_content = "Default content goes here" ## default content when there is no content
    else:
        aboutus_content= aboutus_content.content
        
    return render (request,'about.html',{'aboutus_content':aboutus_content})


def register(request):
    form = RegisterForm()
    if request.method == 'POST':
        form = RegisterForm(request.POST)
        if form.is_valid():
            user =  form.save(commit=False)  ## creates the user data
            user.set_password(form.cleaned_data['password']) # this line of code is used for password HASHING
            user.save() 
            messages.success(request,'Reigistration Successful, Now you can login')
            return redirect('/login')
    
    return render(request, 'register.html', {'form':form})


def login(request):
    form = LoginForm()
    if request.method == 'POST':
        form = LoginForm(request.POST)
        if form.is_valid():
            username = form.cleaned_data['username']
            password = form.cleaned_data['password']
            user = authenticate(username=username,password=password)
            if user is not None:
                auth_login(request,user)
                return redirect('/dashboard')
    return render (request,'login.html',{'form':form})


def dashboard(request):
    blog_title = "My Posts"
    return render (request,'dashboard.html',{'blog_title':blog_title})

def logout(request):
    auth_logout(request)
    return redirect('/index')

def forgot_password(request):
    if request.method == 'POST':
        form = ForgotPasswordForm(request.POST)
        if form.is_valid():
            email = form.cleaned_data['email']
            user = User.objects.get(email = email)
            # send email to reset password
            token = default_token_generator.make_token(user)
            uid= urlsafe_base64_encode(force_bytes(user.pk)) # where pk is a primary 
            current_site = get_current_site(request) #this holds the information about the domain where domain is 127.0.0.1:8000
            domain = current_site.domain
            subject = "Reset Password Requested"    
            message = render_to_string("reset_password_email.html",{'domain' : domain, "uid": uid, 'token': token})

            send_mail(subject,message,'noreply@example.com',[email])
    return render(request,'forgot_password.html')


def reset_password(request):
    pass

myapp/blog/templates/about.html
{% extends "base.html" %}
{% block content %}
<div class="container-fluid ">
    <h3>About Us</h3>
    <div class="d-flex gap-3 justify-content-center mt-5">
        <img src="https://picsum.photos/300/300" alt="....">
        <div class="content">
            {{aboutus_content}}
        </div>
        
    </div>
</div>
{% endblock %}

myapp/blog/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{{blog_title | default:"Document"}}</title> <!-- the default filter gives the default title called "Document"-->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'style.css' %}">

</head>
<body >

    <!-- Header -->
    {% include './includes/header.html' %}
    
    <!-- Footer -->
    {% include './includes/footer.html' %}


    <!-- Dynamic Content -->
    {% block content %}
    {% endblock %}
    
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
</body>
</html>

myapp/blog/templates/contact.html
{% extends 'base.html' %}
{% block content %}
<div class="container-fluid ">
        <div class="d-flex justify-content-center mt-5">
            <div class="d-flex gap-3 flex-column">
                <h3>Contact Form</h3>

            <!-- IN VALID FORM SUBMISSION-->                
                {% for field in form %}
                    {% if  field.errors%}
                    <div class = "col=12">
                        <span class = "fw-bold">{{field.label_tag}}</span>
                        {% for error in field.errors %}
                        <span class = "text-danger">{{error}}</span>
                        
                        {% endfor %}
                    </div>
                    {% endif %}
                    
                {% endfor %}
                <!-- SUCCESSFULL FORM SUBMISSION-->
                {% if success_message %}
                    <div class="alert alert-success" role = "alert">
                        {{success_message}}
                    </div>
                {% endif %}

                <form method="post" class="row g-3">
                    {% csrf_token %}
                    <div class="col-md-6">
                        <label for="name" class="form-label">Name</label>
                        <input type="text" class="form-control" id="name" value="{{name}}" name="name" >
                    </div>
                    <div class="col-md-6">
                        <label for="email" class="form-label">Email</label>
                        <input type="email" class="form-control" id="email"  value="{{email}}" name="email" >
                    </div>
                    <div class="col-12">
                        <label for="message" class="form-label">Message</label>
                        <textarea class="form-control" id="message" value="{{message}}"  name="message" rows="4" ></textarea>
                    </div>
                    <div class="col-12">
                        <button type="submit" class="btn btn-primary">Submit</button>
                    </div>
                </form>
            </div>
        </div>
        
</div>
{% endblock %}
    

myapp/blog/templates/dashboard.html
{% extends 'base.html' %}
{% block content %}
    <div class="container-fluid ">
        <div class="row">
          <div class="col-6">
              <h3> Hi, [USERNAME].</h3>
          </div>
          <div class="col d-flex justify-content-end">
              <div>
                  <h2>Your Groups:</h2>
                  <ul>
                      <li>[GROUP NAME]</li>
                      <li>You are not a member of any groups.</li>
                  </ul>
              </div>
          </div>
        </div>
        <div class="row d-flex justify-content-center">
          <div class="col-6">
              [ERRORS]
          </div>
        </div>
        <div class="row">
          <h2 class="mt-3">{{blog_title}}</h2>
          <div class="d-flex justify-content-center">
              <a href="/newpost" class="btn btn-success">New Post</a>
          </div>
        </div>
        <div class="row m-3">
            <div class="col-4 mb-4">
                <div class="card">
                    <div class="card-body">
                        <div class="row">
                            <div class="col-md-4">
                                <img style="height:300; width:300;" src="https://placehold.co/600x400" class="img-fluid" alt="...">
                            </div>
                            <div class="col-md-8">
                                <h5 class="card-title">[POST TITLE]</h5>
                                <p class="card-text">[POST CONTENT]</p>
                                <div class="d-flex justify-content-between">
                                    <a href="[POST DETAIL URL]">Read More</a>
                                    <a class="text-decoration-none text-dark fw-bold" href="#">[CATEGORY NAME]</a>
                                </div>
                            </div>
                        </div>
                        <div class="d-flex justify-content-between mt-3">
                          <a class="btn btn-info btn-sm text-light" href="[EDIT POST URL]">Edit Post</a>
                          <a class="btn btn-danger btn-sm text-light" href="[DELETE POST URL]">Delete Post</a>
                          <a class="btn btn-success btn-sm text-light" href="[PUBLISH POST URL]">Publish Post</a>
                          <label class="text-danger">Not Published</label>
                        </div>
                    </div>
                </div>
            </div>

        </div>
      </div>
      
{% endblock %}

myapp/blog/templates/detail.html
{% extends 'base.html' %}
{% block content %}


<div class="container-fluid ">
  
  <div class="row">
    <div class="col-lg-8">
      <h1 class="mb-4"> {{post.title}} <small style="font-size:18px"> ({{post.category.name}}) </small> </h1>
      <p class="text-muted">Posted on {{post.created_at|date:"F j, Y"}}</p>
              <img height='400' width='300' src="{{post.img_url}}" class="img-fluid mb-4" alt="Blog Image">
              <p>{{post.content}}</p>
            </div>
            <div class="col-lg-4">
              <div class="card mt-3">
                <div class="card-body">
                  <h5 class="card-title">Related Posts</h5>
                  <ul class="list-unstyled">
                    {% for related_post in related_posts %} 
                    <li><a href="{% url 'blog:detail' slug=related_post.slug %}">{{related_post.title}}</a></li>
                    {% endfor%}

                  </ul>
                </div>
              </div>
            </div>
        </div>
    </div>

{% endblock %}

myapp/blog/templates/forgot_password.html
{% extends 'base.html' %}
{% block content %}
    <div class="container mt-5">
        <div class="row d-flex justify-content-center">
            <div class="col-3 mt-3">
                <h2>Forgot Password</h2>
                <form method="post">
                    <div class="mb-3">
                        <label for="email" class="form-label">Email address</label>
                        <input type="email" class="form-control" id="email" name="email" required>
                    </div>
                    <button type="submit" class="btn btn-primary">Send Password Reset Email</button>
                </form>
                <div class="mt-3">
                    <p>Error: Unable to send email. Please try again later.</p>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

myapp/blog/templates/index.html
{% extends 'base.html' %}

{% block content %}
    <div class="container-fluid ">
        <div class="row">
            <h2 >{{ blog_title|upper}}</h2> <!-- the | symbol must be used before the filter. the upper is known as filter used to uppercase blog_title -->
            <!-- <h2 >{{ blog_title | truncatewords:1 }}</h2>,. the truncate is used to truncate the words in blog_title where 1 denotes after 1 word truncate everything-->
        </div>
        <div class="row m-3"> 
            {% if page_obj%}
                {% for post in page_obj %}
                <div class="col-4 mb-4">
                <div class="card">

                    <div class="card-body">
                        <div class="row">
                            <div class="col-md-4">
                                <img style ="height:300, width: 300" src="{{post.img_url}}" class="img-fluid" alt="...">
                            </div>
                            <div class="col-md-8">
                                <h5 class="card-title">{{post.title}}</h5>
                                <p class="card-text">{{post.content|linebreaks|truncatechars:30}}</p>
                                <div class="d-flex justify-content-between">
                                     <a href="{% url 'blog:detail' slug=post.slug %}">Read More</a>
                                    <a class="text-decoration-none text-dark fw-bold" href="#">{{post.category.name}}</a>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                </div>
                {% endfor %}
                <div class="col-12 my-3">
                    {% if page_obj.has_other_pages %}
                        <nav aria-label="Page navigation">
                            <ul class="pagination">
                                {% if page_obj.has_previous %}
                                    <li class="page-item">
                                        <a class="page-link" href="?page=1" aria-label="First">
                                            <span aria-hidden="true">&laquo; first</span>
                                        </a>
                                    </li>
                                    <li class="page-item">
                                        <a class="page-link" href="?page={{page_obj.previous_page_number}}" aria-label="Previous">
                                            <span aria-hidden="true">previous</span>
                                        </a>
                                    </li>
                                {% endif %}                                                    

                                <li class="page-item"><span class="page-link">{{page_obj.number}} of {{page_obj.paginator.num_pages}}.</span></li>
                                
                                {% if page_obj.has_next %}
                                <li class="page-item">
                                    <a class="page-link" href="?page={{page_obj.next_page_number}}" aria-label="Next">
                                        <span aria-hidden="true">next</span>
                                    </a>
                                </li>
                                <li class="page-item">
                                    <a class="page-link" href="?page={{page_obj.paginator.num_pages}}" aria-label="Last">
                                        <span aria-hidden="true">last &raquo;</span>
                                    </a>
                                </li>
                                {% endif %}
                            </ul>
                        </nav>
                    {% endif %}
                </div>
            {% else %}
                <h2>No Posts Are Availble </h2>
            {% endif %}
        </div>
        
    </div>
{% endblock %}

myapp/blog/templates/login.html
{% extends 'base.html' %}
{% block content %}    
<div class="container-fluid">

        <div class="row d-flex justify-content-center mt-5">
            <div class="col-4">
                <h3>Login</h3>
                <div class="">
                    {% include 'includes/errors.html' %}
                </div>
                <div class="col-12">
                    <span class="text-danger"></span>
                </div>
    
              
        
                <div class="my-3">
                    <form method="post">
                        {% csrf_token %}
                        <div class="form-group">
                            <label for="username" class="form-label">Username</label>
                            <input type="text" class="form-control" id="username" name="username" value="{{ form.username.value|default:''}}">
                        </div>
                       
                        <div class="form-group">
                            <label for="password" class="form-label">Password</label>
                            <input type="password" class="form-control" id="password" name="password">
                        </div>
                       
                        <div class="my-3 d-flex justify-content-between">
                            <a href="{% url 'blog:forgot_password' %}">Forgot Password</a>
                            <button type="submit" class="btn btn-primary">Login</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
    

{% endblock %}

myapp/blog/templates/register.html
{% extends 'base.html' %}
{% block content %}
    <div class="container-fluid">
        <div class="row d-flex justify-content-center mt-5">
            <div class="col-4">
                <h3>Register</h3>
                <div class="">
                    {% include "includes/errors.html" %}
                </div>
                <div class="my-3">
                    <form method="post">
                        {%csrf_token%}
                        <div class="form-group">
                            <label for="username" class="form-label">Username</label>
                            <input type="text" class="form-control" id="username" name="username" value="{{form.username.value|default:''}}">
                        </div>
                        <div class="form-group">
                            <label for="email" class="form-label">Email</label>
                            <input type="email" class="form-control" id="email" name="email" value="{{form.email.value|default:''}}">
                        </div>
                        <div class="form-group">
                            <label for="password" class="form-label">Password</label>
                            <input type="password" class="form-control" id="password" name="password">
                        </div>
                        <div class="form-group">
                            <label for="confirm_password" class="form-label">Confirm Password</label>
                            <input type="password" class="form-control" id="confirm_password" name="password_confirm">
                        </div>
                        <div class="my-3 d-flex justify-content-end">
                            <button type="submit" class="btn btn-primary">Register</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>

{% endblock %}
    

myapp/blog/templates/reset_password_email.html
{% autoescape off %}

Hello,

You requested a reset password for your account at {{domain}}.

Pleas click the link below to reset your password:

http://{{domain}} {% url 'blog:reset_password' uidb64=uid token = token %}


Thank You !!

{% endautoescape %}