myapp/blog/urls.py
from django.urls import path
from . import views

app_name='blog'

urlpatterns=[
    path('details/<str:slug>',views.detail, name='detail'),
    path('index',views.index, name= 'index'),
    path('new_url',views.new_url_view, name= 'new_page_url'),
    path('old_url',views.old_url_redirect, name= 'old_url'),
    path('contact',views.contact, name= 'contact'),
    path('about',views.about, name= 'about'),
    path('register',views.register, name= 'register'),
    path('login',views.login, name = 'login'),
    path('dashboard',views.dashboard,name='dashboard'),
    path('logout',views.logout,name='logout'),
    path('forgot_password',views.forgot_password,name='forgot_password'),
    path('reset_password/<uidb64>/<token>',views.reset_password,name='reset_password'),

]

myapp/myapp/urls.py
from django.contrib import admin
from django.urls import path,include

handler404 = 'myapp.views.custom_page_not_found'

urlpatterns = [
    path('',include('blog.urls')),
    
    path('admin/', admin.site.urls),
]

myapp/blog/models.py
from django.db import models
from django.utils.text import slugify
# Create your models here.


# Category
class Category (models.Model):
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name


class Post(models.Model):
    title = models.CharField(max_length=100)
    content = models.TextField()
    img_url= models.URLField(null=True) # default length is 200. null argument is used to nullable whch means some post doesn't contain images
    created_at = models.DateTimeField(auto_now_add=True)
    slug = models.SlugField(unique=True)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)


    def save(self,*args,**kwargs):
        self.slug = slugify (self.title)
        super().save(*args,**kwargs)
 

    def __str__(self) :
        return self.title


class AboutUs(models.Model):
    content = models.TextField()

myapp/blog/forms.py
from typing import Any
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth import authenticate
class ContactForm(forms.Form):
    name  = forms.CharField(label='Name', max_length= 100, required=True)
    email = forms.EmailField (label="Email",required=True)
    message = forms.CharField(label="Message",required=True)

class RegisterForm(forms.ModelForm):
    username = forms.CharField(label='Username', max_length=100, required=True)
    email = forms.CharField(label='Email', max_length=100, required=True)
    password = forms.CharField(label='Password', max_length=100, required=True)
    password_confirm = forms.CharField(label='Confirm Password', max_length=100, required=True)

    class Meta:
        model  = User
        fields = ['username','email','password']

    def clean(self):
        cleaned_data  = super().clean()
        password = cleaned_data.get('password')
        password_confirm = cleaned_data.get('password_confirm')

        if password and password_confirm and password !=password_confirm:
            raise forms.ValidationError('Password do not match')

class LoginForm (forms.Form):
    username= forms.CharField(label="username",max_length=100,required=True)
    password= forms.CharField(label="password",max_length=100,required=True)

    def clean(self) :
        cleaned_data = super().clean()
        username = cleaned_data.get("username")
        password = cleaned_data.get("password")
        if username and password:
            user = authenticate(username=username,password=password)
            if user is None:
                raise forms.ValidationError("Invalid Username or Password")
            
class ForgotPasswordForm(forms.Form):
    email = forms.EmailField(label="Email",max_length=254, required=True)

    def clean(self):
        cleaned_data=super().clean()
        email = cleaned_data.get('email')

        if not User.objects.filter(email=email).exists():
            raise forms.ValidationError("no user has registered with this mail")

myapp/blog/views.py
from django.shortcuts import render,redirect
from django.http import HttpResponse,Http404
from django.urls import reverse
import logging

from .models import Post,AboutUs
from django.core.paginator import Paginator
from .forms import ContactForm, ForgotPasswordForm, LoginForm, RegisterForm
from django.contrib import messages
from django.contrib.auth import authenticate,login as auth_login, logout as auth_logout
from django.contrib.auth.models import User
from django.contrib.auth.tokens import default_token_generator

from django.utils.http import urlsafe_base64_encode
from django.utils.encoding import force_bytes
from django.contrib.sites.shortcuts import get_current_site
from django.template.loader import render_to_string
from django.core.mail import send_mail

# Create your views here.
# static demo data
#posts=[
#    {'id':1,'title':'Post 1', 'Content': " Content of Post 1"},
#    {'id':2,'title':'Post 2', 'Content': " Content of Post 2"},
#    {'id':3,'title':'Post 3', 'Content': " Content of Post 3"},
#    {'id':4,'title':'Post 4', 'Content': " Content of Post 4"},
#    ]


def index(request):
    blog_title = "Latest Posts" 
    # getting data from post model
    all_posts = Post.objects.all()
    paginator = Paginator(all_posts,5)
    page_number=request.GET.get('page_no')
    page_obj = paginator.get_page(page_number)

    return render(request,'index.html',{'blog_title': blog_title, 'page_obj':page_obj})


def detail(request,slug):
    #getting static data 
    #post=next((item for item in posts if item['id']==id),None)
 
    try:
    # getting data from model by post id
        post=Post.objects.get(slug=slug)
        related_posts = Post.objects.filter(category = post.category).exclude(pk=post.id)
    except Post.DoesNotExist:
        raise Http404("Post Doesn't Exist")
 
    #logger=logging.getLogger("TESTING")
    #logger.debug(f"post variable is {post}")

    return render (request,'detail.html',{'post':post,'related_posts':related_posts})    


def old_url_redirect(request):
    return redirect(reverse('blog:new_page_url'))


def new_url_view(request):
    return HttpResponse("This is the new urls")

def contact(request):
    if request.method == "POST":
        #logger = logging.getLogger("TESTING")
        form=ContactForm(request.POST)
        name = request.POST.get('name')
        email = request.POST.get('email')
        message = request.POST.get('message')
        if form.is_valid():
           #print("HI")

            #print(name)
            print(email)
            #print(message)
            #logger.debug(f"POST data is {name} {email} {message}")
            success_message = 'Your form has been successfully submitted'
            return render(request,'contact.html',{'form':form, 'success_message':success_message})
        else:
            # Handle invalid form case (optional)
            #print("Invalid form submission.")
            #logger.debug(f"POST data is invalid")
            return render(request,'contact.html',{'form':form, 'name':name, 'email':email, 'message': message})

    return render (request,'contact.html')    

def about(request):
    aboutus_content= AboutUs.objects.first()
    if aboutus_content is None or not aboutus_content.content:
        aboutus_content = "Default content goes here" ## default content when there is no content
    else:
        aboutus_content= aboutus_content.content
        
    return render (request,'about.html',{'aboutus_content':aboutus_content})


def register(request):
    form = RegisterForm()
    if request.method == 'POST':
        form = RegisterForm(request.POST)
        if form.is_valid():
            user =  form.save(commit=False)  ## creates the user data
            user.set_password(form.cleaned_data['password']) # this line of code is used for password HASHING
            user.save() 
            messages.success(request,'Reigistration Successful, Now you can login')
            return redirect('/login')
    
    return render(request, 'register.html', {'form':form})


def login(request):
    form = LoginForm()
    if request.method == 'POST':
        form = LoginForm(request.POST)
        if form.is_valid():
            username = form.cleaned_data['username']
            password = form.cleaned_data['password']
            user = authenticate(username=username,password=password)
            if user is not None:
                auth_login(request,user)
                return redirect('/dashboard')
    return render (request,'login.html',{'form':form})


def dashboard(request):
    blog_title = "My Posts"
    return render (request,'dashboard.html',{'blog_title':blog_title})

def logout(request):
    auth_logout(request)
    return redirect('/index')

def forgot_password(request):
    if request.method == 'POST':
        form = ForgotPasswordForm(request.POST)
        if form.is_valid():
            email = form.cleaned_data['email']
            user = User.objects.get(email = email)
            # send email to reset password
            token = default_token_generator.make_token(user)
            uid= urlsafe_base64_encode(force_bytes(user.pk)) # where pk is a primary 
            current_site = get_current_site(request) #this holds the information about the domain where domain is 127.0.0.1:8000
            domain = current_site.domain
            subject = "Reset Password Requested"    
            message = render_to_string("reset_password_email.html",{'domain' : domain, "uid": uid, 'token': token})

            send_mail(subject,message,'noreply@example.com',[email])
    return render(request,'forgot_password.html')


def reset_password(request):
    pass

myapp/blog/templates/includes/errors.html
<!-- Error messages -->
<!-- IN VALID FORM SUBMISSION-->                
{% for field in form %}
{% if  field.errors%}
    <div class = "col=12">
        <span class = "fw-bold">{{field.label_tag}}</span>
        {% for error in field.errors %}
        <span class = "text-danger">{{error}}</span>
        {% endfor %}
    </div>
{% endif %}
{% endfor %}

<!-- Non field Error -->
{% for error in form.non_field_errors %}
<div class = "alert alert-danger "> 
    <span class = "text-dangers">{{ error }}</span>
</div>
{% endfor %}
<!-- Succes messages-->
{% if messages %}
    {% for message in messages %}
        <div class="alert alert-success">
            {{message}}
        </div>
    {% endfor %}
{% endif %}

myapp/blog/templates/includes/footer.html
<!-- These are known as partial templates-->



<footer class="bg-dark text-light p-2 fixed-bottom">
    <div class="col-4 d-flex justify-content-center align-items-center">
      <span class="text-light">© 2021 Company, Inc</span>
    </div>
</footer> 


<!-- 
<footer class="bg-dark text-light p-2 fixed-bottom custom-footer">
  <div class="container d-flex justify-content-center align-items-center">
      <span class="text-light">© 2021 Company, Inc</span>
  </div>
</footer>
-->

myapp/blog/templates/includes/header.html
<!-- These are known as partial templates-->


<header class="p-2 bg-dark text-white">
    <div class="row">
        <div class="col">
            <a class="text-light text-decoration-none" href='/index'> <h3>Blog </h3> </a>
        </div>
        <div class="col">
            <div class="d-flex justify-content-center gap-3">
                <a class="text-light text-decoration-none" href="/index">Home</a>
                <a class="text-light text-decoration-none" href="/about">About</a>
                <a class="text-light text-decoration-none" href="/contact">Contact</a>
                {% if user.is_authenticated %}
                <a class="text-light text-decoration-none" href="{% url 'blog:dashboard' %}">Dashboard</a>
                <a class="text-light text-decoration-none" href="/logout">LogOut</a>
                {% else %}
                <a class="text-light text-decoration-none" href="{% url 'blog:register' %}">Register</a>
                <a class="text-light text-decoration-none" href="{% url 'blog:login' %}">LogIn</a>
                {% endif %}
            </div>
        </div>
    </div>
</header>